/* style */

body{
    margin-top: 20px;
    padding: 0;
    font-family: 'Epilogue';
}
.Logosnap{
    float: left;
    margin: 15px;
    margin-left: 30px;
    margin-top: 7px;
}
nav{
    margin-left: 220px;
    overflow: hidden;
    padding: 1px;
}

nav a{
    text-decoration: none;
    color: #222;
    font-weight: 700;
    padding: 15px 20px;
    font-size: 18px;
    float: left;
}
nav a:hover{
    color: rgb(151, 151, 151);
}
.right{
    float: right;
    margin-right: 45px;
}
.register{
    border-radius: 15px;
    border-style: solid;
    border-width: 1px;
    margin-left: 20px;
}
.middle{
    margin-left: 210px;
}
.imgsection{
    float:right;
    margin-right: 150px;
    margin-top: 90px;
}
.remote{
    display: inline-block;
    font-size: 80px;
    margin-top: 150px;
}
.parag{
    color:rgb(134, 134, 134);
    font-size: 18px;
    font-weight: 700;
    margin-bottom: 60px;
}
.learnmore{
    font-weight: 700;
    border-style: solid;
    border-color: #222;
    border-width: 1px;
    border-radius: 10px;
    padding: 12px 25px;
    color: #222;
    text-decoration: none;
}
.learnmore:hover{
    background-color:rgba(231, 231, 231, 0.37);
}
.bottom{
    margin-left: 200px;
    margin-top: 100px;
}
.bottom img{
    padding: 0px 15px;
}
.attribution{
    position: fixed;
    bottom: 0px;
    left: 40%;
}
.attribution a{
    color: rgb(255, 0, 0);
}
.attribution a:hover{
    color: rgba(155, 0, 0, 0.555);
}
ul{
    position: relative;
    top: 30px;
}
/*hidden{
    display: none;
}
